- title: UN Consolidated Sanctions
  slug: un-sc-sanctions
  category: sanctions
  publisher:
    title: United Nations Security Council
    url: 'https://www.un.org/en/sc/'
  url: 'https://www.un.org/sc/suborg/en/sanctions/un-sc-consolidated-list'
  data:
    url: https://scsanctions.un.org/resources/xml/en/consolidated.xml
    format: XML

- title: CIA World Leaders
  slug: us-cia-world-leaders
  category: pep
  publisher:
    title: US Central Intelligence Agency
    url: https://www.cia.gov/
  url: https://www.cia.gov/library/publications/resources/world-leaders-1/index.html

- title: SDFM Blacklist
  slug: ua-sdfm-blacklist
  category: sanctions
  publisher:
    title: Ukraine State Finance Monitoring Service
    url: http://www.sdfm.gov.ua/
  url: http://www.sdfm.gov.ua/articles.php?cat_id=87&lang=en
  data:
    url: http://www.sdfm.gov.ua/content/file/Site_docs/Black_list/zBlackListFull.xml
    format: XML

- title: Swiss SECO Sanctions/Embargoes
  slug: kg-fiu-national
  category: sanctions
  publisher:
    title: State Secretariat for Economic Affairs (SECO)
    url: https://www.seco.admin.ch/
  url: https://www.seco.admin.ch/seco/en/home/Aussenwirtschaftspolitik_Wirtschaftliche_Zusammenarbeit/Wirtschaftsbeziehungen/exportkontrollen-und-sanktionen/sanktionen-embargos.html
  data:
    url: https://www.sesam.search.admin.ch/sesam-search-web/pages/downloadXmlGesamtliste.xhtml?lang=en&action=downloadXmlGesamtlisteAction
    format: XML

- title: OFAC Consolidated List
  slug: us-ofac
  category: sanctions
  publisher:
    title: US Department of the Treasury
    url: https://www.treasury.gov/
  url: https://www.treasury.gov/resource-center/sanctions/Pages/default.aspx
  data:
    url: https://www.treasury.gov/resource-center/sanctions/SDN-List/Pages/consolidated.aspx
    format: XML

- title: US Denied Persons List
  slug: us-bis-denied
  category: sanctions
  publisher:
    title: US Department of Commerce
    url: https://www.bis.doc.gov/
  url: https://www.bis.doc.gov/index.php/policy-guidance/lists-of-parties-of-concern/denied-persons-list
  data:
    url: https://www.bis.doc.gov/dpl/dpl.txt
    format: txt

- title: GB Consolidated list of targets
  slug: gb-hm-sanctionslist
  category: sanctions
  publisher:
    title: HM Treasury
    url: https://www.gov.uk/
  url: https://www.gov.uk/government/publications/financial-sanctions-consolidated-list-of-targets
  data:
    url: https://www.gov.uk/government/publications/financial-sanctions-consolidated-list-of-targets/consolidated-list-of-targets
    format: html

- title: GB Insolvency Disqualified Directors
  slug: gb-coh-disqualified
  category: finance
  publisher:
    title: The UK Insolvency Service
    url: https://www.insolvencydirect.bis.gov.uk
  url: https://www.insolvencydirect.bis.gov.uk/IESdatabase/viewdirectorsummary-new.asp
  data:
    url: https://www.insolvencydirect.bis.gov.uk/IESdatabase/viewdirectorsummary-new.asp
    format: html

- title: EU EEAS Consolidated Lists
  slug: eu-eeas-sanctions
  category: sanctions
  publisher:
    title: European Union External Action Service
    url: https://eeas.europa.eu/
  url: https://eeas.europa.eu/topics/common-foreign-security-policy-cfsp_en
  data:
    url: https://www.insolvencydirect.bis.gov.uk/IESdatabase/viewdirectorsummary-new.asp
    format: html

- title: CH SECO Sanctions List
  slug: ch-seco-sanctions
  category: sanctions
  publisher:
    title: State Secretariat for Economic Affairs SECO
    url: https://www.seco.admin.ch/
  url: https://www.seco.admin.ch/seco/de/home/Aussenwirtschaftspolitik_Wirtschaftliche_Zusammenarbeit/Wirtschaftsbeziehungen/exportkontrollen-und-sanktionen/sanktionen-embargos.html?_organization=703&_pageIndex=0
  data:
    url: https://www.sesam.search.admin.ch/sesam-search-web/pages/downloadXmlGesamtliste.xhtml?lang=de&action=downloadXmlGesamtlisteAction
    format: xml

- title: KG State FIU National List
  slug: kg-fiu-national
  category: sanctions
  publisher:
    title: State Financial Intelligence Service Under the Government of the Kyrgyz Republic
    url: https://fiu.gov.kg/
  url: https://fiu.gov.kg/sked/1?language=ru
  data: 
    url: http://fiu.gov.kg/uploads/58f843ca071b3.xml
    format: xml

- title: Interpol Red Notices
  slug: interpol-red-notices
  category: crime
  publisher:
    title: Interpol
    url: https://www.interpol.int/
  url: https://www.interpol.int/INTERPOL-expertise/Notices
  data: 
    url: https://www.interpol.int/INTERPOL-expertise/Notices
    format: xml

- title: Every Politician
  slug: everypolitician
  category: pep
  publisher:
    title: Mysociety.org
    url: http://everypolitician.org
  url: http://everypolitician.org
  data: 
    url: https://github.com/everypolitician/everypolitician-data/raw/master/countries.json
    format: JSON

