- slug: un-sc-sanctions
  publisher: 'UN Security Council'
  publisher_url: 'https://www.un.org/en/sc/'
  source: 'Consolidated Sanctions'
  source_url: 'https://www.un.org/sc/suborg/en/sanctions/un-sc-consolidated-list'
