name: interpol_red_notices
description: "[OSANC] Interpol Red Notices"
schedule: daily
pipeline:
  init:
    method: opensanctions.crawlers.interpol_red_notices:scrape
    params:
      url: 'http://www.interpol.int/notice/search/wanted/(offset)/%s'
    handle:
      pass: scrape_case
  scrape_case:
    method: opensanctions.crawlers.interpol_red_notices:scrape_case
    pass: store
  store:
    method: opensanctions.helpers:store_entity